config/routes.rb
Dashboard::Application.routes.draw do
  resources :assignments

  resources :courses

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  root 'sessions#new'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

  

end

app/models/assignment.rb
class Assignment < ActiveRecord::Base
  belongs_to :course
end

app/models/course.rb
class Course < ActiveRecord::Base
  belongs_to :teacher, class_name: 'User'
end

app/models/user.rb
class User < ActiveRecord::Base
  extend Enumerize

  enumerize :group, {:in => {:teacher => 0, :student => 1}, :default => :student}

  validates :name,  presence: true, length: { maximum: 50 }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
            uniqueness: { case_sensitive: false }

  validates :password, length: { minimum: 6 }

  has_secure_password

  before_save { self.email = email.downcase }
  before_create :create_remember_token

  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private
    def create_remember_token
      self.remember_token = User.encrypt(User.new_remember_token)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/assignments_controller.rb
class AssignmentsController < ApplicationController
  include SessionsHelper

  before_action :signed_in_user
  before_action :set_assignment, only: [:show, :edit, :update, :destroy]
  before_action :check_teachers_course, only: [:edit, :update, :destroy]

  # GET /assignments
  # GET /assignments.json
  def index
    @assignments = Assignment.all
  end

  # GET /assignments/1
  # GET /assignments/1.json
  def show
  end

  # GET /assignments/new
  def new
    @assignment = Assignment.new
  end

  # GET /assignments/1/edit
  def edit
  end

  # POST /assignments
  # POST /assignments.json
  def create
    @assignment = Assignment.new(assignment_params)

    respond_to do |format|
      if @assignment.save
        format.html { redirect_to @assignment.course, notice: 'Assignment was successfully created.' }
        format.json { render action: 'show', status: :created, location: @assignment }
      else
        format.html { render action: 'new' }
        format.json { render json: @assignment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /assignments/1
  # PATCH/PUT /assignments/1.json
  def update
    respond_to do |format|
      if @assignment.update(assignment_params)
        format.html { redirect_to @assignment.course, notice: 'Assignment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @assignment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /assignments/1
  # DELETE /assignments/1.json
  def destroy
    @assignment.destroy
    respond_to do |format|
      format.html { redirect_to @assignment.course }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_assignment
      @assignment = Assignment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def assignment_params
      params.require(:assignment).permit(:title, :description, :due_date, :course_id, :active)
    end

    def check_teachers_course
      redirect_to @assignment, notice: 'Only a course\'s teacher may modify its assignments' unless users_course?
    end

    def users_course?
      @assignment.course.teacher == current_user
    end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  include SessionsHelper

  before_action :signed_in_user
  before_action :set_course, only: [:show, :edit, :update, :destroy]

  # GET /courses
  # GET /courses.json
  def index
    @courses = Course.all
  end

  # GET /courses/1
  # GET /courses/1.json
  def show
    @assignments = Assignment.where(:course_id => @course.id).order(:due_date)
    @hide_course_name = true
  end

  # GET /courses/new
  def new
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit
  end

  # POST /courses
  # POST /courses.json
  def create
    @course = Course.new(course_params)

    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: 'Course was successfully created.' }
        format.json { render action: 'show', status: :created, location: @course }
      else
        format.html { render action: 'new' }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1
  # PATCH/PUT /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: 'Course was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    @course.destroy
    respond_to do |format|
      format.html { redirect_to courses_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def course_params
      params.require(:course).permit(:name, :teacher_id)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    user = User.find_by_email(params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      sign_in user
      redirect_to user
    else
      flash.now[:error] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to '/'
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include SessionsHelper

  before_action :signed_in_user

  def show
    @user = User.find(params[:id])

    if @user == current_user # let the user perform actions
      if @user.group.teacher?
        show_teacher
      elsif @user.group.student?
        show_student
      else
        # TODO: handle unknown group
      end
    else # just show general user info
      show_info
    end
  end

  private
    def show_teacher
      @courses = Course.where('teacher_id = ?', @user.id)

      render 'teacher'
    end

    def show_student
      render 'student'
    end

    def show_info
      render 'show'
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "Dashboard"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/assignments_helper.rb
module AssignmentsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.encrypt(remember_token))
    self.current_user = user
  end

  def sign_out
    self.current_user = nil
    cookies.delete(:remember_token)
  end

  def signed_in?
    !current_user.nil?
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    remember_token = User.encrypt(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end

  def signed_in_user
    redirect_to '/signin', notice: 'Please sign in' unless signed_in?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/assignments/_assignments_list.html.erb
<table>
  <thead>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th>Due date</th>
    <% if !defined?(@hide_course_name) || !@hide_course_name %>
      <th>Course</th>
    <% end %>
    <% if current_user.group.teacher? %>
      <th>Active</th>
    <% end %>
    <th></th>
    <th></th>
  </tr>
  </thead>

  <tbody>
  <% @assignments.each do |assignment| %>
    <tr>
      <td><%= assignment.title %></td>
      <td><%= assignment.description %></td>
      <td><%= assignment.due_date %></td>
      <% if !defined?(@hide_course_name) && !@hide_course_name %>
        <td><%= assignment.course.name %></td>
      <% end %>
      <% if current_user.group.teacher? %>
        <td>
          <%= form_for(assignment, :html => { :style => 'margin: 0;' }) do |f| %>
            <%= f.check_box :active, :onclick => 'this.form.submit()' %>
          <% end %>
        </td>
      <% end %>
      <td><%= link_to 'Edit', edit_assignment_path(assignment) %></td>
      <td><%= link_to 'Destroy', assignment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/assignments/_form.html.erb
<%= form_for(@assignment) do |f| %>
  <% if @assignment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@assignment.errors.count, "error") %> prohibited this assignment from being saved:</h2>

      <ul>
      <% @assignment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :due_date %>
    <%= f.datetime_select :due_date %>
  </div>
  <div class="field">
    <%= f.label :course_id %>
    <%= f.select(:course_id, Course.where(:teacher_id => current_user.id).collect { |p| [p.name, p.id]}, selected: params[:course_id]) %>
  </div>
  <div class="field">
    <%= f.label :active %>
    <%= f.check_box :active %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/assignments/edit.html.erb
<h1>Editing assignment</h1>

<%= render 'form' %>

<%= link_to 'Show', @assignment %> |
<%= link_to 'Back', assignments_path %>

app/views/assignments/index.html.erb
<h1>Listing assignments</h1>

<%= render 'assignments/assignments_list' %>

<br>

<%= link_to 'New Assignment', new_assignment_path %>

app/views/assignments/new.html.erb
<h1>New assignment</h1>

<%= render 'form' %>

app/views/assignments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @assignment.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @assignment.description %>
</p>

<p>
  <strong>Due date:</strong>
  <%= @assignment.due_date %>
</p>

<p>
  <strong>Course:</strong>
  <%= @assignment.course_id %>
</p>

<p>
  <strong>Active:</strong>
  <%= @assignment.active %>
</p>

<%= link_to 'Edit', edit_assignment_path(@assignment) %> |
<%= link_to 'Back to Course', course_path(@assignment.course) %>

app/views/courses/_form.html.erb
<%= form_for(@course) do |f| %>
  <% if @course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
      <% @course.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <%= f.hidden_field :teacher_id, :value => current_user.id %><br>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/courses/edit.html.erb
<h1>Editing course</h1>

<%= render 'form' %>

<%= link_to 'Show', @course %> |
<%= link_to 'Back', courses_path %>

app/views/courses/index.html.erb
<h1>Listing courses</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Teacher</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @courses.each do |course| %>
      <tr>
        <td><%= course.name %></td>
        <td><%= course.teacher.name %></td>
        <td><%= link_to 'Show', course %></td>
        <td><%= link_to 'Edit', edit_course_path(course) %></td>
        <td><%= link_to 'Destroy', course, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Create New Course', new_course_path %>

app/views/courses/new.html.erb
<h1>New course</h1>

<%= render 'form' %>

app/views/courses/show.html.erb
<div style="overflow: hidden">
  <div style="float: left">
    <h3><%= @course.name %></h3>
    <h4>Professor: <%= @course.teacher.name %></h4>
  </div>

  <% if @course.teacher == current_user %>
    <div style='float: right;'>
      <%= link_to 'Edit Course', edit_course_path(@course), class: 'btn btn-medium btn-primary' %>
      <%= link_to 'Create Assignment', new_assignment_path(:course_id => @course.id), class: 'btn btn-medium btn-success' %>
    </div>
  <% end %>
</div>

<% if @assignments.empty? %>
  <h2>No assignments</h2>
<% else %>
  <h2>Assignments</h2>
  <%= render 'assignments/assignments_list' %>
<% end %>

app/views/layouts/_cookie.html.erb
<% if Rails.env.development? && signed_in? %>
  <div class="debug_dump">
    Current Cookie:
    <ul>
      <li><%= current_user.name %></li>
      <li><%= current_user.email %></li>
      <li><%= current_user.group %></li>
    </ul>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <thanks>
    Invaluable help from:
    <ul>
      <li><a href="http://railstutorial.org/">Rails Tutorial</a> by Michael Hartl</li>
      <li><a href="http://guides.rubyonrails.org">The official Rails guide</a></li>
    </ul>
  </thanks>
  <me>
    <a href="http://www.linkedin.com/pub/kyle-turney/15/78b/b5b/">My Info</a>
  </me>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "Hogwarts Dashboard", '/', id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <% if signed_in? %>
            <li><%= link_to "Home", {:action => :show, :controller => :users, :id => current_user.id} %></li>
            <li><%= link_to "Sign out", '/signout', method: 'delete' %></li>
          <% else %>
            <li><%= link_to "Sign in", '/signin', method: 'get' %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
  <%= render 'layouts/header' %>
  <div class="container">
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>"><%= value %></div>
    <% end %>
    <%= yield %>
    <%= render 'layouts/footer' %>
    <%= render 'layouts/cookie' %>
    <%= debug(params) if Rails.env.development? %>
  </div>

</body>
</html>

app/views/users/show.html.erb
<div class="row">
  <div class="span6 offset3">
    <h2><%= @user.name %></h2>
    <ul class="user_info">
      <li>Email: <%= @user.email %></li>
      <li>Group: <%= @user.group %></li>
    </ul>
  </div>
</div>

app/views/users/student.html.erb
<h2><%= @user.name %>'s Student Page</h2>

app/views/users/teacher.html.erb
<h3><%= @user.name %>'s Teacher Page</h3>

<div style="overflow: hidden;">
  <div style="float: left">
    <% if @courses.empty? %>
      <h4>No Courses</h4>
    <% else %>
      <h4>Courses</h4>
      <ul class='course-list'>
        <% @courses.each do |course| %>
          <li class="row"><%= link_to course.name, {:action => :show, :controller => :courses, :id => course.id} %></li>
        <% end %>
      </ul>
    <% end %>
  </div>

  <%= link_to 'Create Course', new_course_path, class: 'btn btn-medium btn-success', style: 'float: right' %>
</div>